### PR TITLE
a few tips on readme to get users going

### PR DESCRIPTION
**Pull request by cambro**

### CODE REVIEW

**Review by zploskey — DISMISSED** [review]
The explanation would be better as "Or if you downloaded composer.phar:"

**Comment by cambro** [comment]
I'm not sure that the composer.phar explanation is better, as I had followed the steps up to that point and then received an error because the shell wasn't recognizing the command. Just had to be explicit about what was to be run. You change still gives the right info and users will try it though.

**Comment by zploskey** [comment]
It all depends on how they installed composer. If they installed composer from a linux package manager or by installer the composer executable somewhere in their path then the first command works. If they downloaded the phar file then they will need to run it with the php executable. I didn't care for the wording of calling it a "more explicit command". It's not really, it just depends on how they chose to install the composer executable.

**Comment by zploskey** [comment]
Also, gitignore does not work for files that are checked into the repository. Please back out the change for adding app/config/database.php to .gitignore. It would be fine if we forced them to move the database config from database.php.changeme or something like that, but as it is currently set up git will still show it as modified.

**Comment by cambro** [comment]
Yes good point! I'd definitely recommend implementing something like the following for credentials, where an example file is included but the user is required to create a new file which is then not tracked (as in: https://github.com/UW-Macrostrat/node-api-template)

**Comment by zploskey** [comment]
I think I will set that up, so perhaps we can leave it for now. This looks good to me.

**Pull request merged**
